// jobData.js
export const jobData = [
    {
      id: 1,
      title: "Software Engineer",
      company: "Tech Solutions",
      location: "New York, USA",
      description: "Develop and maintain web applications using modern frameworks.",
      salary: "$80,000 - $100,000",
    },
    {
      id: 2,
      title: "Data Analyst",
      company: "Data Insights Co.",
      location: "San Francisco, USA",
      description: "Analyze data trends and create actionable insights for clients.",
      salary: "$70,000 - $90,000",
    },
    {
      id: 3,
      title: "UI/UX Designer",
      company: "Creative Studio",
      location: "Remote",
      description: "Design user-friendly interfaces and enhance user experiences.",
      salary: "$65,000 - $85,000",
    },
    {
      id: 4,
      title: "Web Developer",
      company: "WebTech Innovations",
      location: "Chicago, IL",
      description: "Build and maintain web applications with a focus on user experience.",
      salary: "$75,000 - $95,000",
    },
    {
      id: 5,
      title: "Product Manager",
      company: "Innovative Solutions",
      location: "Los Angeles, CA",
      description: "Lead the product development process and manage cross-functional teams.",
      salary: "$90,000 - $120,000",
    },
    {
      id: 6,
      title: "Software Engineer",
      company: "Tech Solutions",
      location: "New York, USA",
      description: "Develop and maintain web applications using modern frameworks.",
      salary: "$80,000 - $100,000",
    },
    {
      id: 7,
      title: "Data Analyst",
      company: "Data Insights Co.",
      location: "San Francisco, USA",
      description: "Analyze data trends and create actionable insights for clients.",
      salary: "$70,000 - $90,000",
    },
    {
      id: 8,
      title: "UI/UX Designer",
      company: "Creative Studio",
      location: "Remote",
      description: "Design user-friendly interfaces and enhance user experiences.",
      salary: "$65,000 - $85,000",
    },
    {
      id: 9,
      title: "Web Developer",
      company: "WebTech Innovations",
      location: "Chicago, IL",
      description: "Build and maintain web applications with a focus on user experience.",
      salary: "$75,000 - $95,000",
    },
    {
      id: 10,
      title: "Product Manager",
      company: "Innovative Solutions",
      location: "Los Angeles, CA",
      description: "Lead the product development process and manage cross-functional teams.",
      salary: "$90,000 - $120,000",
    },
    // A
  ];
  